services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: laraveltwelve_webstore
      MYSQL_USER: webstore_admin
      MYSQL_PASSWORD: L4r4v3!12_w3b5t0r3
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
